// Code generated by "goki version"; DO NOT EDIT.

package webki

const (
	// Version is the version of this package being used
	Version = "v0.0.9"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "b1c7fc8"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-12-13 00:31"
)
